FORMAT: 1A
HOST: localhost

# Zomato Uber

APIs descriptions

## Retaurant 

### recommendation  [GET /restaurant/recommendation/{?q}]

+ Parameters
    + lon - lontitude
    + lat - latitude
    + text - last text by user
    + time - 0,1,2,3,4,.....,24

+ Response 200 (application/json)

        [
            {
                name:"Humbles Ray",
                cuisines: [Chinese, Asian Fusin],
                highlights: ['take Away Available', 'breakfast', 'dinner']
                thumb: url,
                userRating: 4.4,
                phoneNumbers: 0386583443,
                lon: 10.22,
                lat:90.11,

            },
            {

            }

        ]
### selection based [GET /restaurant/selectionbased/{?q}]

+ Parameters
    + lon - lontitude
    + lat - latitude
    + text - last text by user
    + categorie - "Breakfast"
    + time  - 0,1,2,3,4,.....,24
    + cuisine - chinese

+ Response 200 (application/json)

        [
            {
                name:"Humbles Ray",
                cuisines: [Chinese, Asian Fusin],
                highlights: ['take Away Available', 'breakfast', 'dinner']
                thumb: url,
                userRating: 4.4,
                phoneNumbers: 0386583443,  -- string
                lon: 10.22,
                lat:90.11,

            }
        ]
        
